
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace ActivityGameBackend.Persistence.Mssql.Words;
public class WordEntityConfiguration : IEntityTypeConfiguration<WordEntity>
{
    public void Configure(EntityTypeBuilder<WordEntity> builder)
    {
        ArgumentNullException.ThrowIfNull(builder);

        builder.ToTable("Words");

        builder.HasKey(w => w.Id);

        builder.Property(w => w.Id)
            .ValueGeneratedOnAdd(); // This sets the Id to be autogenerated

        builder.Property(w => w.Value)
            .IsRequired()
            .HasMaxLength(100);

        builder.Property(w => w.Method)
            .IsRequired()
            .HasConversion<int>();

        builder.Property(m => m.CreatedAtUtc)
            .IsRequired();
    }
}
